config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  #long version
  #get '/pages', to: 'pages#index'
  #get '/pages/:id', to: 'pages#show'
  #post '/pages', to: 'pages#create'
  #put '/pages/:id', to: 'pages#update'
  #delete '/pages/:id', to: 'pages#destroy'

  #short version
  resources :pages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages = Page.all
  end

  def show
    @page = Page.find(params[:id])
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])
    if @page.update(page_params)
      redirect_to page_path(@page)
    else
      render :edit
    end
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new(page_params)
    if @page.save
      redirect_to pages_path
    else
      render :new
    end
  end

  def destroy
    Page.find(params[:id]).destroy
    redirect_to pages_path
  end

  private

  #Strong Params
  def page_params
    params.require(:page).permit(:title, :author, :content, :public)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/edit.html.erb
<h1>Editing: <%= @page.title %></h1>

<%= form_for @page do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, required: true %>
  <br/>
  <%= f.label :author %>
  <%= f.text_field :author, required: true %>
  <br/>
  <%= f.label :content %>
  <%= f.text_area :content, required: true %>
  <br/>
  <%= f.label :public %>
  <%= f.check_box :public %>
  <br/>
  <%= f.submit %>
<% end %>

<%= link_to 'Cancel', page_path(@page), class: 'btn' %>

app/views/pages/index.html.erb
<h1>Pages</h1>

<% if @pages.any? %>
  <% @pages.each do |page| %>
    <h3>
      <%= link_to page.title, page_path(page) %>
    </h3>
  <% end %>

<% else %>
  <h4> No pages, please create one!</h4>
<% end %>

<%= link_to 'New Blog Post', new_page_path, class: 'btn' %>

app/views/pages/new.html.erb
<h1>New Blog Post</h1>

<!--<form method = '/pages' action = 'POST'>
  <input required name = 'title' placeholder='Blog Title'/>
  <br/>
  <input required name = 'author' placeholder='Blog Author'/>
  <br/>
  <textarea required name = 'content' placeholder='Blog Content'></textarea>
  <br/>
  <label>Public?</label>
  <input type = 'checkbox' name = 'public' />
  <br/>
  <input type = 'submit' />
</form>-->

<%= form_for @page do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title, required: true %>
  <br/>
  <%= f.label :author %>
  <%= f.text_field :author, required: true %>
  <br/>
  <%= f.label :content %>
  <%= f.text_area :content, required: true %>
  <br/>
  <%= f.label :public %>
  <%= f.check_box :public %>
  <br/>
  <%= f.submit %>
<% end %>

<%= link_to 'All Posts', pages_path, class: 'btn' %>

app/views/pages/show.html.erb
<h1>
  <%= @page.title %>
</h1>
<blockquote>
  <%= @page.content %>
</blockquote>
<cite>By: <%= @page.author %></cite>
<br/>
<i>Posted on: <%= @page.created_at %></i>
<br/>
<i>Last update: <%= @page.updated_at %></i>

<hr/>

<div class = 'action-buttons'>
  <%= link_to 'Edit', edit_page_path(@page) %>
  <%= link_to 'Delete', page_path(@page),
        method: :delete,
        data: { confirm: 'Really Delete?'} %>
  <%= link_to 'All Posts', pages_path %>
</div>